"""Pure helpers for the coding agent: URL parsing, allow-list, prompt/PR/comment text.

No I/O, no network — unit-tested in isolation.
"""

import re

_ISSUE_RE = re.compile(r"^https?://github\.com/([^/]+)/([^/]+)/issues/(\d+)(?:[#?].*)?$")


def parse_issue_url(url: str) -> tuple[str, str, int]:
    """Extract (owner, repo, issue_number) from a github.com issue URL. Raises ValueError."""
    m = _ISSUE_RE.match(url.strip())
    if not m:
        raise ValueError(f"Not a github.com issue URL: {url!r}")
    return m.group(1), m.group(2), int(m.group(3))


def is_allowed_repo(owner: str, repo: str, allow_list: list[str]) -> bool:
    """Case-insensitive membership of 'owner/repo' in the allow-list."""
    slug = f"{owner}/{repo}".lower()
    return slug in {a.lower() for a in allow_list}


def build_task_prompt(title: str, body: str, *, test_cmd: str) -> str:
    """The implementation prompt handed to the coder."""
    parts = [
        "Implement the following GitHub issue. Keep changes scoped to the issue; "
        "do not refactor unrelated code.",
        f"\n## Issue: {title}\n\n{body}",
    ]
    if test_cmd:
        parts.append(f"\nMake this command pass before you finish: `{test_cmd}`")
    parts.append("\nWhen done, ensure all changes are committed.")
    return "\n".join(parts)


def build_pr_body(issue_url: str) -> str:
    """Draft-PR body that links the issue and marks the PR rotom-generated."""
    return (
        f"Implements {issue_url}\n\n"
        "---\n"
        "🤖 Generated by **rotom** (coding agent). Draft PR — review before merge.\n"
    )


def build_findings_comment(per_reviewer: list[tuple[str, list[dict]]]) -> str:
    """Collate reviewer findings into one severity-tagged markdown comment."""
    lines = ["## 🔎 rotom review findings", ""]
    for name, findings in per_reviewer:
        lines.append(f"### {name}")
        if not findings:
            lines.append("_No findings._")
        else:
            for f in findings:
                sev = str(f.get("severity", "info")).lower()
                title = f.get("title", "(untitled)")
                detail = f.get("detail", "")
                lines.append(f"- **[{sev}]** {title}" + (f" — {detail}" if detail else ""))
        lines.append("")
    lines.append("_Findings are advisory. You decide; merging is the gate._")
    return "\n".join(lines)
